### ISSUE TITLE
Boot from SD-Card

### ISSUE THREAD

**Issue by meAbab** [TechNexion/u-boot-edm#1]
After compile `edm-cf-imx6_defconfig ` I've something below - 

```
  OBJCOPY spl/u-boot-spl.bin
  CFGS    arch/arm/imx-common/spl_sd.cfg.cfgtmp
  MKIMAGE SPL
  OBJCOPY u-boot.srec
  OBJCOPY u-boot.bin
  MKIMAGE u-boot.img
```
According your instruction - 
```

- After the 'make' command completes, the generated 'SPL' and 'u-boot.bin' binary must be flashed into the SD card;

$ sudo dd if=SPL of=/dev/$dev bs=512 seek=2; sync

$ Copy u-boot.img into 1st FAT partition of SD card
```
i did,
```

#dd if=SPL of=/dev/sdd1 bs=512 seek=2;sync
#dd if=u-boot.bin bs=512 seek=2;sync
#cp u-boot.img /dev/sdd1
```
Is it right procedure ? But I'm not able to get anything in serial. With rescue image everything fine.

**Comment by richard-hu** [comment]
Hello,  meAbab :
The second step you post is redundant.
you just need to flash SPL into SD card and put u-boot.img into first FAT partition of SD card.
In the first step, it should be /dev/sdd instead of /dev/sdd1
`
#sudo dd if=SPL of=/dev/sdd bs=512 seek=2;sync
#sudo mkdir /mnt/temp
#sudo mount /dev/sdd1 /mnt/temp
#sudo cp u-boot.img /mnt/temp
#sudo umount /mnt/temp
`

**Comment by richard-hu** [comment]
Hello, meAbab:
Sorry to let you feel confused.
We already update the README file to correct confusing description.
Thank You !!!
